included:
  Sources

disabled_rules:
- identifier_name
- type_body_length
- function_body_length
- cyclomatic_complexity
- operator_whitespace
- nesting
- file_length
- type_name

line_length:
  ignores_comments: true
  warning: 150
  error: 250
force_cast:
  severity: warning
force_try:
  severity: warning
function_parameter_count:
  warning: 10
  error: 12
