name: Integration Tests Dynamic
on:
  push:
    branches:
      - 'main'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  test:
    name: Integration Tests Dynamic
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Bazel output
        id: cache-bazel-output
        uses: actions/cache@v3
        env:
          cache-name: cache-bazel-output
        with:
          path: bazel-output-base
          key: ${{ runner.os }}-integration-dynamic-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-integration-dynamic-${{ env.cache-name }}

      - name: make integration-dynamic
        run: make integration-dynamic
