name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/workflows/renovate_config.js