name: Snapshot Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  test:
    name: Snapshot Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Pods
        id: cache-pods
        uses: actions/cache@v3
        env:
          cache-name: cache-pods
        with:
          path: |
            Tests/Pods
            Tests/Podfile.lock
          key: ${{ runner.os }}-snapshot-tests-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-snapshot-tests-${{ env.cache-name }}

      - name: Cache Bazel output
        id: cache-bazel-output
        uses: actions/cache@v3
        env:
          cache-name: cache-bazel-output
        with:
          path: bazel-output-base
          key: ${{ runner.os }}-snapshot-tests-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-snapshot-tests-${{ env.cache-name }}

      - name: make tests
        run: make tests
