name: Tests
on: [pull_request]
jobs:
  test:
    name: Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: brew install bazelisk
        run: brew install bazelisk
      - name: make tests
        run: make tests
